var age = 25;
age = true;
console.log(age);
age = { name: 'Luigi' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push("Mario");
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: "Luis", age: 18 };
console.log(ninja);
